### ISSUE TITLE
报错解决

### ISSUE THREAD

**Issue by wpsec** [0x727/ShuiZe_0x727#170]
使用docker-compose构建
1. 在宿主机git clone https://github.com/0x727/ShuiZe_0x727.git
2. 进入ShuiZe_0x727创建Dockerfile与docker-compose.yml文件

Dockerfile
```
FROM yankovg/python3.8.2-ubuntu18.04
WORKDIR /

#RUN export https_proxy=http://192.168.188.85:7899
#RUN export http_proxy=http://192.168.188.85:7899
RUN apt update -y
RUN apt install git --fix-missing -y
RUN rm /usr/bin/python3
RUN ln -s /usr/local/bin/python3.8 /usr/bin/python3
RUN python3 -m pip install --upgrade pip
RUN git clone https://github.com/0x727/ShuiZe_0x727
WORKDIR /ShuiZe_0x727
RUN chmod 777 ./docker_build.sh
RUN ./docker_build.sh
ENTRYPOINT [ "python3","/ShuiZe_0x727/ShuiZe.py" ]
```
docker-compose.yml
```
version: "3"
services:
  shuize:
    container_name: shuize
    image: shuize:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./iniFile:/ShuiZe_0x727/iniFile
      - ./result:/ShuiZe_0x727/result
    command:
      -d baidu.com
```
出现Killing shuize  ... done说明构建成功，可以直接ctrl+c
进入容器使用工具
```
docker container exec -it id /bin/bash
```
在宿主机result目录里可以直接看到扫描完的xlsx文件
可在iniFile目录里配置一些信息
