### ISSUE TITLE
提供一个自用的一键部署供参考

### ISSUE THREAD

**Issue by r3x5ur** [0x727/ShuiZe_0x727#99]
## 基于 `docker-compose` 一键安装使用 （好处是环境隔离， 一键安装依赖）
1. 拉下来的仓库添加3个文件
![image](https://user-images.githubusercontent.com/64947085/174205493-73976cac-3213-498c-bbba-697a2e63cf4a.png)
- Dockerfile：
```dockerfile
FROM yankovg/python3.8.2-ubuntu18.04
COPY . /0x727
WORKDIR /
RUN cd /0x727&&\
    rm /usr/bin/python3&&\
    ln -s /usr/local/bin/python3.8 /usr/bin/python3&&\
    apt install python3-setuptools -y&&\
    python3 -m pip install --upgrade pip&&\
    python3 -m pip install -r requirements.txt&&\
    chmod +x ./Plugins/infoGather/subdomain/ksubdomain/ksubdomain_linux
ENTRYPOINT ["tail","-f","/dev/null"]
```
- docker-compose.yml
```yml
version: "3"
services:
  sz0x727:
    build: .
    restart: always
    container_name: sz0x727
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./:/0x727
```
- 0x727
```bash
#!/bin/bash
docker-compose exec -w /0x727  sz0x727 python3 ShuiZe.py $*
```
2. 添加完成之后 `chmod +x 0x727`
3. 运行 `docker-compose up -d`
4. 安装完成之后可以看下 `docker ps`
![image](https://user-images.githubusercontent.com/64947085/174206187-2ea87160-af2b-45d2-a6aa-32e4e2bdd66b.png)
### 使用：`./0x727 -h` (也可以自己加到环境变量中去)
![image](https://user-images.githubusercontent.com/64947085/174206299-9979ecc9-c4cd-4e30-ba72-7d4bd785452f.png)
